const MIME_TYPES: Record<string, string> = {
	icml: 'application/xml',
	idml: 'application/xml',
	strings: 'text/plain',
	csv: 'text/csv',
	dita: 'application/xml',
	mif: 'application/x-mif',
	po: 'text/x-gettext-translation',
	htm: 'text/html',
	html: 'text/html',
	xhtml: 'application/xhtml+xml',
	json: 'application/json',
	md: 'text/markdown',
	markdown: 'text/markdown',
	xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	xlsm: 'application/vnd.ms-excel.sheet.macroEnabled.12',
	xltx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
	xltm: 'application/vnd.ms-excel.template.macroEnabled.12',
	tex: 'application/x-tex',
	pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	pptm: 'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
	ppsx: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
	ppsm: 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',
	potx: 'application/vnd.openxmlformats-officedocument.presentationml.template',
	potm: 'application/vnd.ms-powerpoint.template.macroEnabled.12',
	resx: 'application/xml',
	docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	docm: 'application/vnd.ms-word.document.macroEnabled.12',
	dotx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
	dotm: 'application/vnd.ms-word.template.macroEnabled.12',
	odp: 'application/vnd.oasis.opendocument.presentation',
	otp: 'application/vnd.oasis.opendocument.presentation-template',
	ods: 'application/vnd.oasis.opendocument.spreadsheet',
	ots: 'application/vnd.oasis.opendocument.spreadsheet-template',
	odt: 'application/vnd.oasis.opendocument.text',
	ott: 'application/vnd.oasis.opendocument.text-template',
	php: 'text/x-php',
	txt: 'text/plain',
	pdf: 'application/pdf',
	properties: 'text/x-java-properties',
	txml: 'application/xml',
	srt: 'application/x-subrip',
	tsv: 'text/tab-separated-values',
	ttx: 'application/xml',
	ts: 'text/x-typescript',
	vtt: 'text/vtt',
	wix: 'application/xml',
	xini: 'application/xml',
	xlf: 'application/xliff+xml',
	xliff: 'application/xliff+xml',
	xml: 'application/xml',
	dtd: 'application/xml-dtd',
	yaml: 'application/x-yaml',
};

export function lookupMimeType(extension: string): string {
	return MIME_TYPES[extension.toLowerCase()] || 'application/octet-stream';
}
