import { SupportedFileFormat } from '../types/types';

export const ISO_639_1_LOCALES = [
	'af',
	'ak',
	'am',
	'ar',
	'as',
	'az',
	'ba',
	'be',
	'bg',
	'bm',
	'bn',
	'bo',
	'bs',
	'ca',
	'cs',
	'cy',
	'da',
	'de',
	'dz',
	'ee',
	'el',
	'en',
	'eo',
	'es',
	'et',
	'eu',
	'fa',
	'fi',
	'fj',
	'fo',
	'fr',
	'ga',
	'gd',
	'gl',
	'gn',
	'gu',
	'ha',
	'he',
	'hi',
	'hr',
	'ht',
	'hu',
	'hy',
	'id',
	'ig',
	'is',
	'it',
	'ja',
	'jv',
	'ka',
	'kg',
	'ki',
	'kk',
	'km',
	'kn',
	'ko',
	'ks',
	'ky',
	'la',
	'lb',
	'lg',
	'li',
	'ln',
	'lo',
	'lt',
	'lv',
	'mg',
	'mi',
	'mk',
	'ml',
	'mn',
	'mr',
	'ms',
	'mt',
	'my',
	'nb',
	'ne',
	'nl',
	'ny',
	'oc',
	'or',
	'pa',
	'pl',
	'ps',
	'pt',
	'rn',
	'ro',
	'ru',
	'rw',
	'sa',
	'sc',
	'sd',
	'sg',
	'si',
	'sk',
	'sl',
	'sm',
	'sn',
	'so',
	'sq',
	'sr',
	'ss',
	'st',
	'su',
	'sv',
	'sw',
	'ta',
	'te',
	'tg',
	'th',
	'ti',
	'tk',
	'tl',
	'tn',
	'tr',
	'ts',
	'tt',
	'tw',
	'ug',
	'uk',
	'ur',
	'vi',
	'wo',
	'xh',
	'yo',
	'zh',
	'zu',
];

export const ISO_639_3_LOCALES = [
	'ace',
	'als',
	'ast',
	'awa',
	'ayr',
	'azb',
	'ban',
	'bem',
	'bho',
	'bjn',
	'bug',
	'ceb',
	'cjk',
	'ckb',
	'crh',
	'dik',
	'diq',
	'dyu',
	'fil',
	'fon',
	'fur',
	'fuv',
	'gaz',
	'hne',
	'ilo',
	'kab',
	'kac',
	'kam',
	'kas',
	'kbp',
	'kea',
	'khk',
	'kmb',
	'kmr',
	'knc',
	'lij',
	'lmo',
	'ltg',
	'lua',
	'luo',
	'lus',
	'mag',
	'mai',
	'min',
	'mni',
	'mos',
	'nso',
	'nus',
	'pag',
	'pap',
	'pbt',
	'plt',
	'prs',
	'quy',
	'sat',
	'scn',
	'shn',
	'szl',
	'taq',
	'tpi',
	'tum',
	'tzm',
	'umb',
	'uzn',
	'vec',
	'vls',
	'war',
	'ydd',
];

export const BCP_47_LOCALES = [
	'ace-ID',
	'af-ZA',
	'ak-GH',
	'als-AL',
	'am-ET',
	'ar-SA',
	'as-IN',
	'ast-ES',
	'awa-IN',
	'ayr-BO',
	'az-AZ',
	'azb-AZ',
	'ba-RU',
	'ban-ID',
	'be-BY',
	'bem-ZM',
	'bg-BG',
	'bho-IN',
	'bjn-ID',
	'bm-ML',
	'bn-BD',
	'bo-CN',
	'bs-BA',
	'bug-ID',
	'ca-ES',
	'ceb-PH',
	'cjk-AO',
	'ckb-IQ',
	'crh-RU',
	'cs-CZ',
	'cy-GB',
	'da-DK',
	'de-DE',
	'dik-SS',
	'diq-TR',
	'dyu-CI',
	'dz-BT',
	'ee-GH',
	'el-GR',
	'en-AU',
	'en-CA',
	'en-GB',
	'en-IE',
	'en-US',
	'eo-EU',
	'es-419',
	'es-AR',
	'es-ES',
	'es-MX',
	'et-EE',
	'eu-ES',
	'fa-IR',
	'fi-FI',
	'fil-PH',
	'fj-FJ',
	'fo-FO',
	'fon-BJ',
	'fr-CA',
	'fr-FR',
	'fur-IT',
	'fuv-NG',
	'ga-IE',
	'gaz-ET',
	'gd-GB',
	'gl-ES',
	'gn-PY',
	'gu-IN',
	'ha-NE',
	'he-IL',
	'hi-IN',
	'hne-IN',
	'hr-HR',
	'ht-HT',
	'hu-HU',
	'hy-AM',
	'id-ID',
	'ig-NG',
	'ilo-PH',
	'is-IS',
	'it-IT',
	'ja-JP',
	'jv-ID',
	'ka-GE',
	'kab-DZ',
	'kac-MM',
	'kam-KE',
	'kas-IN',
	'kbp-TG',
	'kea-CV',
	'kg-CG',
	'khk-MN',
	'ki-KE',
	'kk-KZ',
	'km-KH',
	'kmb-AO',
	'kmr-TR',
	'kn-IN',
	'knc-NG',
	'ko-KR',
	'ks-IN',
	'ky-KG',
	'la-VA',
	'lb-LU',
	'lg-UG',
	'li-NL',
	'lij-IT',
	'lmo-IT',
	'ln-CD',
	'lo-LA',
	'lt-LT',
	'ltg-LV',
	'lua-CD',
	'luo-KE',
	'lus-IN',
	'lv-LV',
	'mag-IN',
	'mai-IN',
	'mg-MG',
	'mi-NZ',
	'min-ID',
	'mk-MK',
	'ml-IN',
	'mn-MN',
	'mni-IN',
	'mos-BF',
	'mr-IN',
	'ms-MY',
	'mt-MT',
	'my-MM',
	'nb-NO',
	'ne-NP',
	'nl-BE',
	'nl-NL',
	'nso-ZA',
	'nus-SS',
	'ny-MW',
	'oc-FR',
	'or-IN',
	'pa-IN',
	'pag-PH',
	'pap-CW',
	'pbt-PK',
	'pl-PL',
	'plt-MG',
	'prs-AF',
	'ps-PK',
	'pt-BR',
	'pt-PT',
	'quy-PE',
	'rn-BI',
	'ro-RO',
	'ru-RU',
	'rw-RW',
	'sa-IN',
	'sat-IN',
	'sc-IT',
	'scn-IT',
	'sd-PK',
	'sg-CF',
	'shn-MM',
	'si-LK',
	'sk-SK',
	'sl-SI',
	'sm-WS',
	'sn-ZW',
	'so-SO',
	'sq-AL',
	'sr-Cyrl-RS',
	'sr-Latn-RS',
	'ss-SZ',
	'st-LS',
	'su-ID',
	'sv-SE',
	'sw-KE',
	'szl-PL',
	'ta-IN',
	'taq-ML',
	'te-IN',
	'tg-TJ',
	'th-TH',
	'ti-ET',
	'tk-TM',
	'tl-PH',
	'tn-ZA',
	'tpi-PG',
	'tr-TR',
	'ts-ZA',
	'tt-RU',
	'tum-MW',
	'tw-GH',
	'tzm-MA',
	'ug-CN',
	'uk-UA',
	'umb-AO',
	'ur-PK',
	'uzn-UZ',
	'vec-IT',
	'vi-VN',
	'vls-BE',
	'war-PH',
	'wo-SN',
	'xh-ZA',
	'ydd-US',
	'yo-NG',
	'zh-CN',
	'zh-HK',
	'zh-TW',
	'zu-ZA',
];

const supportedLanguages: string[] = [
	...ISO_639_1_LOCALES,
	...ISO_639_3_LOCALES,
	...BCP_47_LOCALES,
];

export const supportedLanguageSet = new Set(supportedLanguages);

export const languageMapping: Record<string, string> = {
	ace: 'Acehnese',
	'ace-ID': 'Acehnese',
	af: 'Afrikaans',
	'af-ZA': 'Afrikaans',
	ak: 'Akan',
	'ak-GH': 'Akan',
	als: 'Tosk Albanian',
	'als-AL': 'Tosk Albanian',
	am: 'Amharic',
	'am-ET': 'Amharic',
	ar: 'Arabic',
	'ar-SA': 'Arabic',
	as: 'Assamese',
	'as-IN': 'Assamese',
	ast: 'Asturian',
	'ast-ES': 'Asturian',
	awa: 'Awadhi',
	'awa-IN': 'Awadhi',
	ayr: 'Central Aymara',
	'ayr-BO': 'Central Aymara',
	az: 'Azerbaijani',
	'az-AZ': 'Azerbaijani',
	azb: 'South Azerbaijani',
	'azb-AZ': 'South Azerbaijani',
	ba: 'Bashkir',
	'ba-RU': 'Bashkir',
	ban: 'Balinese',
	'ban-ID': 'Balinese',
	be: 'Belarusian',
	'be-BY': 'Belarusian',
	bem: 'Bemba',
	'bem-ZM': 'Bemba',
	bg: 'Bulgarian',
	'bg-BG': 'Bulgarian',
	bho: 'Bhojpuri',
	'bho-IN': 'Bhojpuri',
	bjn: 'Banjar',
	'bjn-ID': 'Banjar',
	bm: 'Bambara',
	'bm-ML': 'Bambara',
	bn: 'Bengali',
	'bn-BD': 'Bengali',
	bo: 'Tibetan',
	'bo-CN': 'Tibetan',
	bs: 'Bosnian',
	'bs-BA': 'Bosnian',
	bug: 'Buginese',
	'bug-ID': 'Buginese',
	ca: 'Catalan',
	'ca-ES': 'Catalan',
	ceb: 'Cebuano',
	'ceb-PH': 'Cebuano',
	cjk: 'Chokwe',
	'cjk-AO': 'Chokwe',
	ckb: 'Kurdish Sorani',
	'ckb-IQ': 'Kurdish Sorani',
	crh: 'Crimean Tatar',
	'crh-RU': 'Crimean Tatar',
	cs: 'Czech',
	'cs-CZ': 'Czech',
	cy: 'Welsh',
	'cy-GB': 'Welsh',
	da: 'Danish',
	'da-DK': 'Danish',
	de: 'German',
	'de-DE': 'German',
	dik: 'Dinka',
	'dik-SS': 'Dinka',
	diq: 'Dimli',
	'diq-TR': 'Dimli',
	dyu: 'Dyula',
	'dyu-CI': 'Dyula',
	dz: 'Dzongkha',
	'dz-BT': 'Dzongkha',
	ee: 'Ewe',
	'ee-GH': 'Ewe',
	el: 'Greek',
	'el-GR': 'Greek',
	en: 'English',
	'en-AU': 'English (Australia)',
	'en-CA': 'English (Canada)',
	'en-GB': 'English (United Kingdom)',
	'en-IE': 'English (Ireland)',
	'en-US': 'English (United States)',
	eo: 'Esperanto',
	'eo-EU': 'Esperanto',
	es: 'Spanish',
	'es-419': 'Spanish (Latin America)',
	'es-AR': 'Spanish (Argentina)',
	'es-ES': 'Spanish',
	'es-MX': 'Spanish (Mexico)',
	et: 'Estonian',
	'et-EE': 'Estonian',
	eu: 'Basque',
	'eu-ES': 'Basque',
	fa: 'Persian',
	'fa-IR': 'Persian',
	fi: 'Finnish',
	'fi-FI': 'Finnish',
	fil: 'Filipino',
	'fil-PH': 'Filipino',
	fj: 'Fijian',
	'fj-FJ': 'Fijian',
	fo: 'Faroese',
	'fo-FO': 'Faroese',
	fon: 'Fon',
	'fon-BJ': 'Fon',
	fr: 'French',
	'fr-CA': 'French (Canada)',
	'fr-FR': 'French',
	fur: 'Friulian',
	'fur-IT': 'Friulian',
	fuv: 'Nigerian Fulfulde',
	'fuv-NG': 'Nigerian Fulfulde',
	ga: 'Irish',
	'ga-IE': 'Irish',
	gaz: 'West Central Oromo',
	'gaz-ET': 'West Central Oromo',
	gd: 'Scottish Gaelic',
	'gd-GB': 'Scottish Gaelic',
	gl: 'Galician',
	'gl-ES': 'Galician',
	gn: 'Guaraní',
	'gn-PY': 'Guaraní',
	gu: 'Gujarati',
	'gu-IN': 'Gujarati',
	ha: 'Hausa',
	'ha-NE': 'Hausa',
	he: 'Hebrew',
	'he-IL': 'Hebrew',
	hi: 'Hindi',
	'hi-IN': 'Hindi',
	hne: 'Chhattisgarhi',
	'hne-IN': 'Chhattisgarhi',
	hr: 'Croatian',
	'hr-HR': 'Croatian',
	ht: 'Haitian Creole',
	'ht-HT': 'Haitian Creole',
	hu: 'Hungarian',
	'hu-HU': 'Hungarian',
	hy: 'Armenian',
	'hy-AM': 'Armenian',
	id: 'Indonesian',
	'id-ID': 'Indonesian',
	ig: 'Igbo',
	'ig-NG': 'Igbo',
	ilo: 'Iloko',
	'ilo-PH': 'Iloko',
	is: 'Icelandic',
	'is-IS': 'Icelandic',
	it: 'Italian',
	'it-IT': 'Italian',
	ja: 'Japanese',
	'ja-JP': 'Japanese',
	jv: 'Javanese',
	'jv-ID': 'Javanese',
	ka: 'Georgian',
	'ka-GE': 'Georgian',
	kab: 'Kabyle',
	'kab-DZ': 'Kabyle',
	kac: 'Jingpho',
	'kac-MM': 'Jingpho',
	kam: 'Kamba',
	'kam-KE': 'Kamba',
	kas: 'Kashmiri (Arabic script)',
	'kas-IN': 'Kashmiri (Arabic script)',
	kbp: 'Kabiyè',
	'kbp-TG': 'Kabiyè',
	kea: 'Kabuverdianu',
	'kea-CV': 'Kabuverdianu',
	kg: 'Kongo',
	'kg-CG': 'Kongo',
	khk: 'Halh Mongolian',
	'khk-MN': 'Halh Mongolian',
	ki: 'Kikuyu',
	'ki-KE': 'Kikuyu',
	kk: 'Kazakh',
	'kk-KZ': 'Kazakh',
	km: 'Khmer',
	'km-KH': 'Khmer',
	kmb: 'Kimbundu',
	'kmb-AO': 'Kimbundu',
	kmr: 'Northern Kurdish',
	'kmr-TR': 'Northern Kurdish',
	kn: 'Kannada',
	'kn-IN': 'Kannada',
	knc: 'Central Kanuri',
	'knc-NG': 'Central Kanuri',
	ko: 'Korean',
	'ko-KR': 'Korean',
	ks: 'Kashmiri (Devanagari script)',
	'ks-IN': 'Kashmiri (Devanagari script)',
	ky: 'Kyrgyz',
	'ky-KG': 'Kyrgyz',
	la: 'Latin',
	'la-VA': 'Latin',
	lb: 'Luxembourgish',
	'lb-LU': 'Luxembourgish',
	lg: 'Luganda',
	'lg-UG': 'Luganda',
	li: 'Limburgish',
	'li-NL': 'Limburgish',
	lij: 'Ligurian',
	'lij-IT': 'Ligurian',
	lmo: 'Lombard',
	'lmo-IT': 'Lombard',
	ln: 'Lingala',
	'ln-CD': 'Lingala',
	lo: 'Lao',
	'lo-LA': 'Lao',
	lt: 'Lithuanian',
	'lt-LT': 'Lithuanian',
	ltg: 'Latgalian',
	'ltg-LV': 'Latgalian',
	lua: 'Luba-Lulua',
	'lua-CD': 'Luba-Lulua',
	luo: 'Luo',
	'luo-KE': 'Luo',
	lus: 'Mizo',
	'lus-IN': 'Mizo',
	lv: 'Latvian',
	'lv-LV': 'Latvian',
	mag: 'Magahi',
	'mag-IN': 'Magahi',
	mai: 'Maithili',
	'mai-IN': 'Maithili',
	mg: 'Malagasy',
	'mg-MG': 'Malagasy',
	mi: 'Maori',
	'mi-NZ': 'Maori',
	min: 'Minangkabau',
	'min-ID': 'Minangkabau',
	mk: 'Macedonian',
	'mk-MK': 'Macedonian',
	ml: 'Malayalam',
	'ml-IN': 'Malayalam',
	mn: 'Mongolian',
	'mn-MN': 'Mongolian',
	mni: 'Manipuri',
	'mni-IN': 'Manipuri',
	mos: 'Mossi',
	'mos-BF': 'Mossi',
	mr: 'Marathi',
	'mr-IN': 'Marathi',
	ms: 'Malay',
	'ms-MY': 'Malay',
	mt: 'Maltese',
	'mt-MT': 'Maltese',
	my: 'Burmese',
	'my-MM': 'Burmese',
	nb: 'Norwegian Bokmål',
	'nb-NO': 'Norwegian Bokmål',
	ne: 'Nepali',
	'ne-NP': 'Nepali',
	nl: 'Dutch',
	'nl-BE': 'Dutch (Belgium)',
	'nl-NL': 'Dutch',
	nso: 'Northern Sotho',
	'nso-ZA': 'Northern Sotho',
	nus: 'Nuer',
	'nus-SS': 'Nuer',
	ny: 'Nyanja',
	'ny-MW': 'Nyanja',
	oc: 'Occitan',
	'oc-FR': 'Occitan',
	or: 'Odia',
	'or-IN': 'Odia',
	pa: 'Punjabi',
	'pa-IN': 'Punjabi',
	pag: 'Pangasinan',
	'pag-PH': 'Pangasinan',
	pap: 'Papiamento',
	'pap-CW': 'Papiamento',
	pbt: 'Southern Pashto',
	'pbt-PK': 'Southern Pashto',
	pl: 'Polish',
	'pl-PL': 'Polish',
	plt: 'Plateau Malagasy',
	'plt-MG': 'Plateau Malagasy',
	prs: 'Dari',
	'prs-AF': 'Dari',
	ps: 'Pashto',
	'ps-PK': 'Pashto',
	pt: 'Portuguese',
	'pt-BR': 'Portuguese (Brazil)',
	'pt-PT': 'Portuguese (Portugal)',
	quy: 'Ayacucho Quechua',
	'quy-PE': 'Ayacucho Quechua',
	rn: 'Kirundi',
	'rn-BI': 'Kirundi',
	ro: 'Romanian',
	'ro-RO': 'Romanian',
	ru: 'Russian',
	'ru-RU': 'Russian',
	rw: 'Kinyarwanda',
	'rw-RW': 'Kinyarwanda',
	sa: 'Sanskrit',
	'sa-IN': 'Sanskrit',
	sat: 'Santali',
	'sat-IN': 'Santali',
	sc: 'Sardinian',
	'sc-IT': 'Sardinian',
	scn: 'Sicilian',
	'scn-IT': 'Sicilian',
	sd: 'Sindhi',
	'sd-PK': 'Sindhi',
	sg: 'Sango',
	'sg-CF': 'Sango',
	shn: 'Shan',
	'shn-MM': 'Shan',
	si: 'Sinhala',
	'si-LK': 'Sinhala',
	sk: 'Slovak',
	'sk-SK': 'Slovak',
	sl: 'Slovenian',
	'sl-SI': 'Slovenian',
	sm: 'Samoan',
	'sm-WS': 'Samoan',
	sn: 'Shona',
	'sn-ZW': 'Shona',
	so: 'Somali',
	'so-SO': 'Somali',
	sq: 'Albanian',
	'sq-AL': 'Albanian',
	sr: 'Serbian',
	'sr-Cyrl-RS': 'Serbian (Cyrillic script)',
	'sr-Latn-RS': 'Serbian (Latin script)',
	ss: 'Swati',
	'ss-SZ': 'Swati',
	st: 'Southern Sotho',
	'st-LS': 'Southern Sotho',
	su: 'Sundanese',
	'su-ID': 'Sundanese',
	sv: 'Swedish',
	'sv-SE': 'Swedish',
	sw: 'Swahili',
	'sw-KE': 'Swahili',
	szl: 'Silesian',
	'szl-PL': 'Silesian',
	ta: 'Tamil',
	'ta-IN': 'Tamil',
	taq: 'Tamasheq',
	'taq-ML': 'Tamasheq',
	te: 'Telugu',
	'te-IN': 'Telugu',
	tg: 'Tajik',
	'tg-TJ': 'Tajik',
	th: 'Thai',
	'th-TH': 'Thai',
	ti: 'Tigrinya',
	'ti-ET': 'Tigrinya',
	tk: 'Turkmen',
	'tk-TM': 'Turkmen',
	tl: 'Tagalog',
	'tl-PH': 'Tagalog',
	tn: 'Tswana',
	'tn-ZA': 'Tswana',
	tpi: 'Tok Pisin',
	'tpi-PG': 'Tok Pisin',
	tr: 'Turkish',
	'tr-TR': 'Turkish',
	ts: 'Tsonga',
	'ts-ZA': 'Tsonga',
	tt: 'Tatar',
	'tt-RU': 'Tatar',
	tum: 'Tumbuka',
	'tum-MW': 'Tumbuka',
	tw: 'Twi',
	'tw-GH': 'Twi',
	tzm: 'Central Atlas Tamazight',
	'tzm-MA': 'Central Atlas Tamazight',
	ug: 'Uyghur',
	'ug-CN': 'Uyghur',
	uk: 'Ukrainian',
	'uk-UA': 'Ukrainian',
	umb: 'Umbundu',
	'umb-AO': 'Umbundu',
	ur: 'Urdu',
	'ur-PK': 'Urdu',
	uzn: 'Uzbek',
	'uzn-UZ': 'Uzbek',
	vec: 'Venetian',
	'vec-IT': 'Venetian',
	vi: 'Vietnamese',
	'vi-VN': 'Vietnamese',
	vls: 'West Flemish',
	'vls-BE': 'West Flemish',
	war: 'Waray',
	'war-PH': 'Waray',
	wo: 'Wolof',
	'wo-SN': 'Wolof',
	xh: 'Xhosa',
	'xh-ZA': 'Xhosa',
	ydd: 'Yiddish',
	'ydd-US': 'Yiddish',
	yo: 'Yoruba',
	'yo-NG': 'Yoruba',
	zh: 'Chinese',
	'zh-CN': 'Chinese (Simplified)',
	'zh-HK': 'Chinese (Traditional, Hong Kong)',
	'zh-TW': 'Chinese (Traditional)',
	zu: 'Zulu',
	'zu-ZA': 'Zulu',
};

const supportedFileFormats: SupportedFileFormat[] = [
	{
		name: 'Adobe InCopy (ICML)',
		extensions: ['icml'],
		description: 'Adobe InCopy ICML format',
	},
	{
		name: 'Adobe InDesign (IDML)',
		extensions: ['idml'],
		description: 'Adobe InDesign IDML format',
	},
	{
		name: 'Apple Strings',
		extensions: ['strings'],
		description: 'Apple localization strings format',
	},
	{
		name: 'Comma Separated Values (CSV)',
		extensions: ['csv'],
		description: 'CSV file format',
	},
	{
		name: 'Darwin Information Typing Architecture (DITA)',
		extensions: ['dita'],
		description: 'DITA XML format',
	},
	{
		name: 'FrameMaker MIF',
		extensions: ['mif'],
		description: 'FrameMaker MIF format',
	},
	{
		name: 'Gettext PO',
		extensions: ['po'],
		description: 'Gettext Portable Object format',
	},
	{
		name: 'HTML',
		extensions: ['htm', 'html', 'xhtml'],
		description: 'HTML and XHTML formats',
	},
	{
		name: 'JSON',
		extensions: ['json'],
		description: 'JSON file format',
	},
	{
		name: 'Markdown',
		extensions: ['md', 'markdown'],
		description: 'Markdown format',
	},
	{
		name: 'Microsoft Excel (XLSX)',
		extensions: ['xlsx'],
		description: 'Microsoft Excel format',
	},
	{
		name: 'Excel Macro-Enabled Workbook (XLSM)',
		extensions: ['xlsm'],
		description: 'Excel workbook with macros',
	},
	{
		name: 'Excel Template (XLTX)',
		extensions: ['xltx'],
		description: 'Excel template format',
	},
	{
		name: 'Excel Macro-Enabled Template (XLTM)',
		extensions: ['xltm'],
		description: 'Excel template with macros',
	},
	{
		name: 'LaTeX',
		extensions: ['tex'],
		description: 'LaTeX document format',
	},
	{
		name: 'Microsoft PowerPoint (PPTX)',
		extensions: ['pptx'],
		description: 'PowerPoint presentation format',
	},
	{
		name: 'PowerPoint Macro-Enabled (PPTM)',
		extensions: ['pptm'],
		description: 'PowerPoint with macros',
	},
	{
		name: 'PowerPoint Presentation (PPSX)',
		extensions: ['ppsx'],
		description: 'PowerPoint slideshow format',
	},
	{
		name: 'PowerPoint Macro-Enabled Presentation (PPSM)',
		extensions: ['ppsm'],
		description: 'PowerPoint slideshow with macros',
	},
	{
		name: 'PowerPoint Template (POTX)',
		extensions: ['potx'],
		description: 'PowerPoint template format',
	},
	{
		name: 'PowerPoint Macro-Enabled Template (POTM)',
		extensions: ['potm'],
		description: 'PowerPoint template with macros',
	},
	{
		name: 'Microsoft RESX',
		extensions: ['resx'],
		description: 'Microsoft .NET resource format',
	},
	{
		name: 'Microsoft Word (DOCX)',
		extensions: ['docx'],
		description: 'Microsoft Word document format',
	},
	{
		name: 'Word Macro-Enabled Document (DOCM)',
		extensions: ['docm'],
		description: 'Word document with macros',
	},
	{
		name: 'Word Template (DOTX)',
		extensions: ['dotx'],
		description: 'Word template format',
	},
	{
		name: 'Word Macro-Enabled Template (DOTM)',
		extensions: ['dotm'],
		description: 'Word template with macros',
	},
	{
		name: 'OpenDocument Presentation (ODP)',
		extensions: ['odp'],
		description: 'OpenDocument presentation format',
	},
	{
		name: 'OpenDocument Presentation Template (OTP)',
		extensions: ['otp'],
		description: 'OpenDocument presentation template',
	},
	{
		name: 'OpenDocument Spreadsheet (ODS)',
		extensions: ['ods'],
		description: 'OpenDocument spreadsheet format',
	},
	{
		name: 'OpenDocument Spreadsheet Template (OTS)',
		extensions: ['ots'],
		description: 'OpenDocument spreadsheet template',
	},
	{
		name: 'OpenDocument Text (ODT)',
		extensions: ['odt'],
		description: 'OpenDocument text format',
	},
	{
		name: 'OpenDocument Text Template (OTT)',
		extensions: ['ott'],
		description: 'OpenDocument text template',
	},
	{
		name: 'PHP',
		extensions: ['php'],
		description: 'PHP source code format',
	},
	{
		name: 'Plain Text',
		extensions: ['txt'],
		description: 'Plain text format',
	},
	{
		name: 'Portable Document Format (PDF)',
		extensions: ['pdf'],
		description: 'PDF document format',
	},
	{
		name: 'Properties',
		extensions: ['properties'],
		description: 'Java properties file format',
	},
	{
		name: 'SDL Trados TXML',
		extensions: ['txml'],
		description: 'SDL Trados TXML format',
	},
	{
		name: 'SubRip Subtitles (SRT)',
		extensions: ['srt'],
		description: 'SubRip subtitle format',
	},
	{
		name: 'Tab Separated Values (TSV)',
		extensions: ['tsv'],
		description: 'Tab-separated values format',
	},
	{
		name: 'TRADOS TTX',
		extensions: ['ttx'],
		description: 'TRADOS TTX format',
	},
	{
		name: 'TypeScript',
		extensions: ['ts'],
		description: 'TypeScript source code format',
	},
	{
		name: 'WebVTT Subtitle',
		extensions: ['vtt'],
		description: 'WebVTT subtitle format',
	},
	{
		name: 'WIX Localization',
		extensions: ['wix'],
		description: 'WIX localization format',
	},
	{
		name: 'XINI',
		extensions: ['xini'],
		description: 'XINI format',
	},
	{
		name: 'XLIFF',
		extensions: ['xlf', 'xliff'],
		description: 'XML Localization Interchange File Format',
	},
	{
		name: 'XML',
		extensions: ['xml', 'dtd'],
		description: 'XML and DTD formats',
	},
	{
		name: 'YAML',
		extensions: ['yaml'],
		description: 'YAML format',
	},
];

export const supportedExtensionsSet = new Set(supportedFileFormats.flatMap((f) => f.extensions));
