import { SupportedFileFormat } from '../types/types';

export const ISO_639_1_LOCALES = [
	'af',
	'ak',
	'am',
	'ar',
	'as',
	'az',
	'ba',
	'be',
	'bg',
	'bm',
	'bn',
	'bo',
	'bs',
	'ca',
	'cs',
	'cy',
	'da',
	'de',
	'dz',
	'ee',
	'el',
	'en',
	'eo',
	'es',
	'et',
	'eu',
	'fa',
	'fi',
	'fj',
	'fo',
	'fr',
	'ga',
	'gd',
	'gl',
	'gn',
	'gu',
	'ha',
	'he',
	'hi',
	'hr',
	'ht',
	'hu',
	'hy',
	'id',
	'ig',
	'is',
	'it',
	'ja',
	'jv',
	'ka',
	'kg',
	'ki',
	'kk',
	'km',
	'kn',
	'ko',
	'ks',
	'ky',
	'la',
	'lb',
	'lg',
	'li',
	'ln',
	'lo',
	'lt',
	'lv',
	'mg',
	'mi',
	'mk',
	'ml',
	'mn',
	'mr',
	'ms',
	'mt',
	'my',
	'nb',
	'ne',
	'nl',
	'ny',
	'oc',
	'or',
	'pa',
	'pl',
	'pt',
	'ps',
	'rn',
	'ro',
	'ru',
	'rw',
	'sa',
	'sc',
	'sd',
	'sg',
	'si',
	'sk',
	'sl',
	'sm',
	'sn',
	'so',
	'sq',
	'sr',
	'ss',
	'st',
	'su',
	'sv',
	'sw',
	'ta',
	'te',
	'tg',
	'th',
	'ti',
	'tk',
	'tl',
	'tn',
	'tr',
	'ts',
	'tt',
	'tw',
	'ug',
	'uk',
	'ur',
	'vi',
	'wo',
	'xh',
	'yo',
	'zu',
	'zh',
];

export const ISO_639_3_LOCALES = [
	'ace',
	'als',
	'ast',
	'awa',
	'ayr',
	'azb',
	'ban',
	'bem',
	'bho',
	'bjn',
	'bug',
	'ceb',
	'cjk',
	'ckb',
	'crh',
	'dik',
	'diq',
	'dyu',
	'fil',
	'fon',
	'fur',
	'fuv',
	'gaz',
	'hne',
	'ilo',
	'kab',
	'kac',
	'kam',
	'kas',
	'kbp',
	'kea',
	'khk',
	'kmb',
	'kmr',
	'knc',
	'lij',
	'lmo',
	'ltg',
	'lua',
	'luo',
	'lus',
	'mag',
	'mai',
	'min',
	'mni',
	'mos',
	'nso',
	'nus',
	'pag',
	'pap',
	'pbt',
	'plt',
	'prs',
	'quy',
	'sat',
	'scn',
	'shn',
	'szl',
	'taq',
	'tpi',
	'tum',
	'tzm',
	'umb',
	'uzn',
	'vec',
	'vls',
	'war',
	'ydd',
];

export const BCP_47_LOCALES = ['en-GB', 'en-US', 'pt-BR', 'pt-PT', 'zh-CN', 'zh-TW'];

const supportedLanguages: string[] = [
	...ISO_639_1_LOCALES,
	...ISO_639_3_LOCALES,
	...BCP_47_LOCALES,
];

export const supportedLanguageSet = new Set(supportedLanguages);

export const languageMapping: Record<string, string> = {
	ace: 'Acehnese',
	af: 'Afrikaans',
	ak: 'Akan',
	als: 'Tosk Albanian',
	am: 'Amharic',
	ar: 'Arabic',
	as: 'Assamese',
	ast: 'Asturian',
	awa: 'Awadhi',
	ayr: 'Central Aymara',
	az: 'Azerbaijani',
	azb: 'South Azerbaijani',
	ba: 'Bashkir',
	ban: 'Balinese',
	be: 'Belarusian',
	bem: 'Bemba',
	bg: 'Bulgarian',
	bho: 'Bhojpuri',
	bjn: 'Banjar',
	bm: 'Bambara',
	bn: 'Bengali',
	bo: 'Tibetan',
	bs: 'Bosnian',
	bug: 'Buginese',
	ca: 'Catalan',
	ceb: 'Cebuano',
	cjk: 'Chokwe',
	ckb: 'Central Kurdish',
	crh: 'Crimean Tatar',
	cs: 'Czech',
	cy: 'Welsh',
	da: 'Danish',
	de: 'German',
	dik: 'Dinka',
	diq: 'Dimli',
	dyu: 'Dyula',
	dz: 'Dzongkha',
	ee: 'Ewe',
	el: 'Greek',
	en: 'English',
	'en-GB': 'English (United Kingdom)',
	'en-US': 'English (United States)',
	eo: 'Esperanto',
	es: 'Spanish',
	et: 'Estonian',
	eu: 'Basque',
	fa: 'Persian',
	fi: 'Finnish',
	fil: 'Filipino',
	fj: 'Fijian',
	fo: 'Faroese',
	fon: 'Fon',
	fr: 'French',
	fur: 'Friulian',
	fuv: 'Nigerian Fulfulde',
	ga: 'Irish',
	gaz: 'West Central Oromo',
	gd: 'Scottish Gaelic',
	gl: 'Galician',
	gn: 'Guarani',
	gu: 'Gujarati',
	ha: 'Hausa',
	he: 'Hebrew',
	hi: 'Hindi',
	hne: 'Chhattisgarhi',
	hr: 'Croatian',
	ht: 'Haitian',
	hu: 'Hungarian',
	hy: 'Armenian',
	id: 'Indonesian',
	ig: 'Igbo',
	ilo: 'Iloko',
	is: 'Icelandic',
	it: 'Italian',
	ja: 'Japanese',
	jv: 'Javanese',
	ka: 'Georgian',
	kab: 'Kabyle',
	kac: 'Jingpho',
	kam: 'Kamba',
	kas: 'Arabic Kashmiri',
	kbp: 'Kabiyè',
	kea: 'Kabuverdianu',
	kg: 'Kongo',
	khk: 'Halh Mongolian',
	ki: 'Kikuyu',
	kk: 'Kazakh',
	km: 'Khmer',
	kmb: 'Kimbundu',
	kmr: 'Northern Kurdish',
	kn: 'Kannada',
	knc: 'Central Kanuri',
	ko: 'Korean',
	ks: 'Devanagari Kashmiri',
	ky: 'Kyrgyz',
	la: 'Latin',
	lb: 'Luxembourgish',
	lg: 'Ganda',
	li: 'Limburgish',
	lij: 'Ligurian',
	lmo: 'Lombard',
	ln: 'Lingala',
	lo: 'Lao',
	lt: 'Lithuanian',
	ltg: 'Latgalian',
	lua: 'Luba-Lulua',
	luo: 'Luo',
	lus: 'Mizo',
	lv: 'Latvian',
	mag: 'Magahi',
	mai: 'Maithili',
	mg: 'Malagasy',
	mi: 'Maori',
	min: 'Minangkabau',
	mk: 'Macedonian',
	ml: 'Malayalam',
	mn: 'Mongolian',
	mni: 'Manipuri',
	mos: 'Mossi',
	mr: 'Marathi',
	ms: 'Malay',
	mt: 'Maltese',
	my: 'Burmese',
	nb: 'Norwegian Bokmål',
	ne: 'Nepali',
	nl: 'Dutch',
	nso: 'Northern Sotho',
	nus: 'Nuer',
	ny: 'Nyanja',
	oc: 'Occitan',
	or: 'Odia',
	pa: 'Punjabi',
	pag: 'Pangasinan',
	pap: 'Papiamento',
	pbt: 'Southern Pashto',
	pl: 'Polish',
	plt: 'Plateau Malagasy',
	prs: 'Dari',
	ps: 'Pashto',
	pt: 'Portuguese',
	'pt-BR': 'Portuguese (Brazil)',
	'pt-PT': 'Portuguese (Portugal)',
	quy: 'Ayacucho Quechua',
	rn: 'Rundi',
	ro: 'Romanian',
	ru: 'Russian',
	rw: 'Kinyarwanda',
	sa: 'Sanskrit',
	sat: 'Santali',
	sc: 'Sardinian',
	scn: 'Sicilian',
	sd: 'Sindhi',
	sg: 'Sango',
	shn: 'Shan',
	si: 'Sinhala',
	sk: 'Slovak',
	sl: 'Slovenian',
	sm: 'Samoan',
	sn: 'Shona',
	so: 'Somali',
	sq: 'Albanian',
	sr: 'Serbian',
	ss: 'Swati',
	st: 'Southern Sotho',
	su: 'Sundanese',
	sv: 'Swedish',
	sw: 'Swahili',
	szl: 'Silesian',
	ta: 'Tamil',
	taq: 'Tamasheq',
	te: 'Telugu',
	tg: 'Tajik',
	th: 'Thai',
	ti: 'Tigrinya',
	tk: 'Turkmen',
	tl: 'Tagalog',
	tn: 'Tswana',
	tpi: 'Tok Pisin',
	tr: 'Turkish',
	ts: 'Tsonga',
	tt: 'Tatar',
	tum: 'Tumbuka',
	tw: 'Twi',
	tzm: 'Tamazight',
	ug: 'Uyghur',
	uk: 'Ukrainian',
	umb: 'Umbundu',
	ur: 'Urdu',
	uzn: 'Uzbek',
	vec: 'Venetian',
	vi: 'Vietnamese',
	vls: 'West Flemish',
	war: 'Waray',
	wo: 'Wolof',
	xh: 'Xhosa',
	ydd: 'Yiddish',
	yo: 'Yoruba',
	zh: 'Chinese',
	'zh-CN': 'Chinese (Simplified)',
	'zh-TW': 'Chinese (Traditional)',
	zu: 'Zulu',
};

const supportedFileFormats: SupportedFileFormat[] = [
	{
		name: 'Adobe InCopy (ICML)',
		extensions: ['icml'],
		description: 'Adobe InCopy ICML format',
	},
	{
		name: 'Adobe InDesign (IDML)',
		extensions: ['idml'],
		description: 'Adobe InDesign IDML format',
	},
	{
		name: 'Apple Strings',
		extensions: ['strings'],
		description: 'Apple localization strings format',
	},
	{
		name: 'Comma Separated Values (CSV)',
		extensions: ['csv'],
		description: 'CSV file format',
	},
	{
		name: 'Darwin Information Typing Architecture (DITA)',
		extensions: ['dita'],
		description: 'DITA XML format',
	},
	{
		name: 'FrameMaker MIF',
		extensions: ['mif'],
		description: 'FrameMaker MIF format',
	},
	{
		name: 'Gettext PO',
		extensions: ['po'],
		description: 'Gettext Portable Object format',
	},
	{
		name: 'HTML',
		extensions: ['htm', 'html', 'xhtml'],
		description: 'HTML and XHTML formats',
	},
	{
		name: 'JSON',
		extensions: ['json'],
		description: 'JSON file format',
	},
	{
		name: 'Markdown',
		extensions: ['md', 'markdown'],
		description: 'Markdown format',
	},
	{
		name: 'Microsoft Excel (XLSX)',
		extensions: ['xlsx'],
		description: 'Microsoft Excel format',
	},
	{
		name: 'Excel Macro-Enabled Workbook (XLSM)',
		extensions: ['xlsm'],
		description: 'Excel workbook with macros',
	},
	{
		name: 'Excel Template (XLTX)',
		extensions: ['xltx'],
		description: 'Excel template format',
	},
	{
		name: 'Excel Macro-Enabled Template (XLTM)',
		extensions: ['xltm'],
		description: 'Excel template with macros',
	},
	{
		name: 'LaTeX',
		extensions: ['tex'],
		description: 'LaTeX document format',
	},
	{
		name: 'Microsoft PowerPoint (PPTX)',
		extensions: ['pptx'],
		description: 'PowerPoint presentation format',
	},
	{
		name: 'PowerPoint Macro-Enabled (PPTM)',
		extensions: ['pptm'],
		description: 'PowerPoint with macros',
	},
	{
		name: 'PowerPoint Presentation (PPSX)',
		extensions: ['ppsx'],
		description: 'PowerPoint slideshow format',
	},
	{
		name: 'PowerPoint Macro-Enabled Presentation (PPSM)',
		extensions: ['ppsm'],
		description: 'PowerPoint slideshow with macros',
	},
	{
		name: 'PowerPoint Template (POTX)',
		extensions: ['potx'],
		description: 'PowerPoint template format',
	},
	{
		name: 'PowerPoint Macro-Enabled Template (POTM)',
		extensions: ['potm'],
		description: 'PowerPoint template with macros',
	},
	{
		name: 'Microsoft RESX',
		extensions: ['resx'],
		description: 'Microsoft .NET resource format',
	},
	{
		name: 'Microsoft Word (DOCX)',
		extensions: ['docx'],
		description: 'Microsoft Word document format',
	},
	{
		name: 'Word Macro-Enabled Document (DOCM)',
		extensions: ['docm'],
		description: 'Word document with macros',
	},
	{
		name: 'Word Template (DOTX)',
		extensions: ['dotx'],
		description: 'Word template format',
	},
	{
		name: 'Word Macro-Enabled Template (DOTM)',
		extensions: ['dotm'],
		description: 'Word template with macros',
	},
	{
		name: 'OpenDocument Presentation (ODP)',
		extensions: ['odp'],
		description: 'OpenDocument presentation format',
	},
	{
		name: 'OpenDocument Presentation Template (OTP)',
		extensions: ['otp'],
		description: 'OpenDocument presentation template',
	},
	{
		name: 'OpenDocument Spreadsheet (ODS)',
		extensions: ['ods'],
		description: 'OpenDocument spreadsheet format',
	},
	{
		name: 'OpenDocument Spreadsheet Template (OTS)',
		extensions: ['ots'],
		description: 'OpenDocument spreadsheet template',
	},
	{
		name: 'OpenDocument Text (ODT)',
		extensions: ['odt'],
		description: 'OpenDocument text format',
	},
	{
		name: 'OpenDocument Text Template (OTT)',
		extensions: ['ott'],
		description: 'OpenDocument text template',
	},
	{
		name: 'PHP',
		extensions: ['php'],
		description: 'PHP source code format',
	},
	{
		name: 'Plain Text',
		extensions: ['txt'],
		description: 'Plain text format',
	},
	{
		name: 'Portable Document Format (PDF)',
		extensions: ['pdf'],
		description: 'PDF document format',
	},
	{
		name: 'Properties',
		extensions: ['properties'],
		description: 'Java properties file format',
	},
	{
		name: 'SDL Trados TXML',
		extensions: ['txml'],
		description: 'SDL Trados TXML format',
	},
	{
		name: 'SubRip Subtitles (SRT)',
		extensions: ['srt'],
		description: 'SubRip subtitle format',
	},
	{
		name: 'Tab Separated Values (TSV)',
		extensions: ['tsv'],
		description: 'Tab-separated values format',
	},
	{
		name: 'TRADOS TTX',
		extensions: ['ttx'],
		description: 'TRADOS TTX format',
	},
	{
		name: 'TypeScript',
		extensions: ['ts'],
		description: 'TypeScript source code format',
	},
	{
		name: 'WebVTT Subtitle',
		extensions: ['vtt'],
		description: 'WebVTT subtitle format',
	},
	{
		name: 'WIX Localization',
		extensions: ['wix'],
		description: 'WIX localization format',
	},
	{
		name: 'XINI',
		extensions: ['xini'],
		description: 'XINI format',
	},
	{
		name: 'XLIFF',
		extensions: ['xlf', 'xliff'],
		description: 'XML Localization Interchange File Format',
	},
	{
		name: 'XML',
		extensions: ['xml', 'dtd'],
		description: 'XML and DTD formats',
	},
	{
		name: 'YAML',
		extensions: ['yaml'],
		description: 'YAML format',
	},
];

export const supportedExtensionsSet = new Set(supportedFileFormats.flatMap((f) => f.extensions));
